name: 🚀 Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main   # deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./public   # adjust if needed (for Laravel use `public`)
          server-dir: /htdocs/  # InfinityFree public root
